### ISSUE TITLE
Trouble running 

### ISSUE THREAD

**Issue by rkoniuta** [dblanding/cadviewer#2]
Good afternoon Doug - I wanted to get your opinion on an error I am now receiving when trying to run the program

Executing on PythonOCC-Core 7.72 yields:

ImportError: cannot import name 'BRepAdaptor_HCurve' from 'OCC.Core.BRepAdaptor'

Have you encountered this? I would be appreciative for your advice

**Comment by dblanding** [comment]
No, I haven't seen this error. I would offer to look into it if I could, but I'm afraid this code has gone unmaintained for several years now, so you are most likely on your own here...

**Comment by rkoniuta** [comment]
Got it. I assume just a versioning challenge. Would you happen to know which package versions/ python version worked while you were testing this years ago? Thank you.

**Comment by dblanding** [comment]
In the readme there is a link to a [screenshot](https://dblanding.github.io/cadviewer/) that shows it running on PythonOCC-7.4.0-rc1which I would have installed under conda.
